# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.9.3
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/backend: registry
    io.containers.autoupdate/mosquitto: registry
    io.containers.autoupdate/backup: registry
    io.containers.autoupdate/backup-redundant: registry
  labels:
    app: homeassistant
  name: homeassistant
spec:
  containers:
  - image: docker.io/library/eclipse-mosquitto:latest
    name: mosquitto
    args:
    - /usr/sbin/mosquitto
    - -c
    - /mosquitto/config/mosquitto.conf
    ports:
    - containerPort: 1883 #MQTT
      hostPort: 1883
    - containerPort: 9001 #Websocket
      hostPort: 9001
    volumeMounts:
    - mountPath: /mosquitto/config
      name: mnt-homeassistant-mosquitto-config
    - mountPath: /mosquitto/data
      name: mnt-homeassistant-mosquitto-data
    - mountPath: /mosquitto/log
      name: mnt-homeassistant-mosquitto-log
    env:
      - name: TZ
        value: Europe/Berlin
  - image: docker.io/grafana/grafana
    name: grafana
    ports:
      - containerPort: 3000
        HostPort: 8084
    volumeMounts:
    - mountPath: /var/lib/grafana
      name: mnt-homeassistant-grafana
  - image: docker.io/library/influxdb
    name: influxdb
#    ports:
#      - containerPort: 8086
#        HostPort: 8086
    env:
      - name: DOCKER_INFLUXDB_INIT_MODE
        value: setup
      - name: DOCKER_INFLUXDB_INIT_USERNAME
        value: homeassistant
      - name: DOCKER_INFLUXDB_INIT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: homeassistant
            key: influxdb_user_pw
      - name: DOCKER_INFLUXDB_INIT_ORG
        value: sebastianyue
      - name: DOCKER_INFLUXDB_INIT_BUCKET
        value: homeassistant
    volumeMounts:
    - mountPath: /var/lib/influxdb2
      name: mnt-homeassistant-influxdb-data
    - mountPath: /etc/influxdb2
      name: mnt-homeassistant-influxdb-config
  - image: ghcr.io/home-assistant/home-assistant:stable
    name: backend
    securityContext:
      procMount: Unmasked
      capabilities:
        add:
          - SYS_RAWIO
    volumeMounts:
    - mountPath: /dev/ttyACM0
      name: dev-homeassistant-backend-zigbee-dongle
    - mountPath: /config
      name: mnt-homeassistant-backend-config
    ports:
      - containerPort: 8123
        hostPort: 8123
  - name: backup
    image: docker.io/sebgad/restainer:latest
    env:
      - name: RESTIC_TAG
        value: homeassistant
      - name: RESTIC_FORGET_ARGS
        value: --keep-daily 28 --keep-weekly 12 --keep-monthly 12 --group-by paths --prune
      - name: RESTIC_PASSWORD
        valueFrom:
          secretKeyRef:
            name: homeassistant
            key: restic_pw
      - name: TERM
        value: xterm
      - name: BACKUP_CRON
        value: "0 5 * * *"
      - name: CHECK_CRON
        value: "0 22 * * *"
    args:
      - tail
      - -fn0
      - /var/log/cron.log
    volumeMounts:
      - mountPath: /mnt/repo
        name: mnt-homeassistant-backup-host-path
      - mountPath: /data
        name: mnt-homeassistant-backup-data-path
      - mountPath: /etc/timezone
        name: etc-timezone
      - mountPath: /etc/localtime
        name: etc-localtime
      - mountPath: /var/log
        name: mnt-homeassistant-backup-log-path
  - name: backup-redundant
    image: docker.io/sebgad/restainer:latest
    env:
      - name: RESTIC_TAG
        value: homeassistant-redundant
      - name: RESTIC_FORGET_ARGS
        value: --keep-daily 28 --keep-weekly 12 --keep-monthly 12 --group-by paths --prune
      - name: RESTIC_PASSWORD
        valueFrom:
          secretKeyRef:
            name: homeassistant
            key: restic_pw
      - name: TERM
        value: xterm
      - name: BACKUP_CRON
        value: "0 5 * * *"
      - name: CHECK_CRON
        value: "0 22 * * *"
    args:
      - tail
      - -fn0
      - /var/log/cron.log
    volumeMounts:
      - mountPath: /mnt/repo
        name: mnt-clouddrive-backup-redundant-homeassistant
      - mountPath: /data
        name: mnt-homeassistant-backup-data-path
      - mountPath: /etc/timezone
        name: etc-timezone
      - mountPath: /etc/localtime
        name: etc-localtime
      - mountPath: /var/log
        name: mnt-homeassistant-backup-redundant-log-path
  volumes:
  - hostPath:
      path: /opt/pods/homeassistant/mosquitto_eclipse/config
      type: Directory
    name: mnt-homeassistant-mosquitto-config
  - hostPath:
      path: /opt/pods/homeassistant/mosquitto_eclipse/data
      type: Directory
    name: mnt-homeassistant-mosquitto-data
  - hostPath:
      path: /opt/pods/homeassistant/mosquitto_eclipse/log
      type: Directory
    name: mnt-homeassistant-mosquitto-log
  - hostPath:
      path: /opt/pods/homeassistant/homeassistant
      type: Directory
    name: mnt-homeassistant-backend-config
  - hostPath:
      path: /opt/pods/homeassistant
      type: Directory
    name: mnt-homeassistant-backup-data-path
  - hostPath:
      path: /mnt/clouddrive_backup/backup_redundant/homeassistant
      type: Directory
    name: mnt-clouddrive-backup-redundant-homeassistant
  - hostPath:
      path: /mnt/clouddrive_backup/backup/homeassistant
      type: Directory
    name: mnt-homeassistant-backup-host-path
  - hostPath:
      path: /etc/timezone
      type: Directory
    name: etc-timezone
  - hostPath:
      path: /etc/localtime
      type: Directory
    name: etc-localtime
  - hostPath:
      path: /opt/pods/homeassistant/backup
      type: Directory
    name: mnt-homeassistant-backup-log-path
  - hostPath:
      path: /opt/pods/homeassistant/backup_redundant
      type: Directory
    name: mnt-homeassistant-backup-redundant-log-path
  - hostPath:
      path: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231214202959-if00
      type: CharDevice
    name: dev-homeassistant-backend-zigbee-dongle
  - hostPath:
      path: /opt/pods/homeassistant/grafana
      type: Directory
    name: mnt-homeassistant-grafana
  - hostPath:
      path: /opt/pods/homeassistant/influxdb/data
      type: Directory
    name: mnt-homeassistant-influxdb-data
  - hostPath:
      path: /opt/pods/homeassistant/influxdb/config
      type: Directory
    name: mnt-homeassistant-influxdb-config
