apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/mosquitto: registry
    io.containers.autoupdate/grafana: registry
    io.containers.autoupdate/influxdb: registry
    io.containers.autoupdate/backend: registry
    io.containers.autoupdate/zigbee2mqtt: registry
  labels:
    app: homeassistant
  name: homeassistant
spec:
  restartPolicy: always
  containers:
  - name: mosquitto
    image: docker.io/library/eclipse-mosquitto:latest
    args:
    - /usr/sbin/mosquitto
    - -c
    - /mosquitto/config/mosquitto.conf
    ports:
    - containerPort: 1883 #MQTT
      hostPort: 1883
    - containerPort: 9001 #Websocket
      hostPort: 9001
    volumeMounts:
    - mountPath: /mosquitto/config
      name: mnt-homeassistant-mosquitto-config
    - mountPath: /mosquitto/data
      name: mnt-homeassistant-mosquitto-data
    - mountPath: /mosquitto/log
      name: mnt-homeassistant-mosquitto-log
    env:
      - name: TZ
        value: Europe/Berlin
  - name: grafana
    image: docker.io/grafana/grafana
    ports:
      - containerPort: 3000
        HostPort: 8084
    volumeMounts:
    - mountPath: /var/lib/grafana
      name: mnt-homeassistant-grafana
  - name: influxdb
    image: docker.io/library/influxdb
    env:
      - name: DOCKER_INFLUXDB_INIT_MODE
        value: setup
      - name: DOCKER_INFLUXDB_INIT_USERNAME
        value: homeassistant
      - name: DOCKER_INFLUXDB_INIT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: homeassistant
            key: influxdb_user_pw
      - name: DOCKER_INFLUXDB_INIT_ORG
        value: sebastianyue
      - name: DOCKER_INFLUXDB_INIT_BUCKET
        value: homeassistant
    volumeMounts:
    - mountPath: /var/lib/influxdb2
      name: mnt-homeassistant-influxdb-data
    - mountPath: /etc/influxdb2
      name: mnt-homeassistant-influxdb-config
    ports:
      - containerPort: 8086
        hostPort: 8089
  - name: backend
    image: ghcr.io/home-assistant/home-assistant:stable
    volumeMounts:
    - mountPath: /config
      name: mnt-homeassistant-backend-config
    - mountPath: /etc/localtime
      name: etc-localtime
    - mountPath: /etc/timezone
      name: etc-timezone
    ports:
      - containerPort: 8123
        hostPort: 8123
  - name: zigbee2mqtt
    image: docker.io/koenkk/zigbee2mqtt
    env:
      - name: TZ
        value: Europe/Berlin
    volumeMounts:
    - mountPath: /app/data
      name: mnt-homeassistant-zigbee2mqtt-data-path
    - mountPath: /dev/ttyACM0
      name: dev-homeassistant-backend-zigbee-dongle
    ports:
    - containerPort: 8080
      hostPort: 8088
  volumes:
  - hostPath:
      path: /kubernetes/homeassistant/mosquitto_eclipse/config
      type: Directory
    name: mnt-homeassistant-mosquitto-config
  - hostPath:
      path: /kubernetes/homeassistant/mosquitto_eclipse/data
      type: Directory
    name: mnt-homeassistant-mosquitto-data
  - hostPath:
      path: /kubernetes/homeassistant/mosquitto_eclipse/log
      type: Directory
    name: mnt-homeassistant-mosquitto-log
  - hostPath:
      path: /kubernetes/homeassistant/homeassistant
      type: Directory
    name: mnt-homeassistant-backend-config
  - hostPath:
      path: /etc/timezone
      type: Directory
    name: etc-timezone
  - hostPath:
      path: /etc/localtime
      type: Directory
    name: etc-localtime
  - hostPath:
      path: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231214202959-if00
      type: CharDevice
    name: dev-homeassistant-backend-zigbee-dongle
  - hostPath:
      path: /kubernetes/homeassistant/grafana
      type: Directory
    name: mnt-homeassistant-grafana
  - hostPath:
      path: /kubernetes/homeassistant/influxdb/data
      type: Directory
    name: mnt-homeassistant-influxdb-data
  - hostPath:
      path: /kubernetes/homeassistant/influxdb/config
      type: Directory
    name: mnt-homeassistant-influxdb-config
  - hostPath:
      path: /kubernetes/homeassistant/zigbee2mqtt
      type: Directory
    name: mnt-homeassistant-zigbee2mqtt-data-path
