apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/backend: registry
    io.containers.autoupdate/backup-config: image
    io.containers.autoupdate/backup-media: image
    io.containers.autoupdate/backup-redundant-config: image
    io.containers.autoupdate/backup-redundant-media: image
  labels:
    app: jellyfin
  name: jellyfin
spec:
  containers:
  - name: backend
    image: docker.io/jellyfin/jellyfin:latest
    ports:
    - containerPort: 8096
      hostPort: 8096
    volumeMounts:
    - mountPath: /config
      name: mnt-jellyfin-config
    - mountPath: /cache
      name: mnt-jellyfin-cache
    - mountPath: /media
      name: mnt-jellyfin-media
  - name: backup-config
    image: docker.io/sebgad/restainer:latest
    env:
      - name: RESTIC_TAG
        value: jellyfin-config
      - name: RESTIC_FORGET_ARGS
        value: --keep-daily 28 --keep-weekly 12 --keep-monthly 12 --group-by paths --prune
      - name: RESTIC_PASSWORD
        valueFrom:
          secretKeyRef:
            name: jellyfin
            key: restic_pw
      - name: TERM
        value: xterm
      - name: BACKUP_CRON
        value: "0 5 * * *"
      - name: CHECK_CRON
        value: "0 22 * * *"
    args:
      - tail
      - -fn0
      - /var/log/cron.log
    volumeMounts:
      - mountPath: /mnt/repo
        name: mnt-jellyfin-backup-config-host-path
      - mountPath: /data
        name: mnt-jellyfin-config
      - mountPath: /etc/timezone
        name: etc-timezone
      - mountPath: /etc/localtime
        name: etc-localtime
  - name: backup-media
    image: docker.io/sebgad/restainer:latest
    env:
      - name: RESTIC_TAG
        value: jellyfin-media
      - name: RESTIC_FORGET_ARGS
        value: --keep-daily 28 --keep-weekly 12 --keep-monthly 12 --group-by paths --prune
      - name: RESTIC_PASSWORD
        valueFrom:
          secretKeyRef:
            name: jellyfin
            key: restic_pw
      - name: TERM
        value: xterm
      - name: BACKUP_CRON
        value: "0 5 * * *"
      - name: CHECK_CRON
        value: "0 22 * * *"
    args:
      - tail
      - -fn0
      - /var/log/cron.log
    volumeMounts:
      - mountPath: /mnt/repo
        name: mnt-jellyfin-backup-media-host-path
      - mountPath: /data
        name: mnt-jellyfin-media
      - mountPath: /etc/timezone
        name: etc-timezone
      - mountPath: /etc/localtime
        name: etc-localtime
  - name: backup-redundant-config
    image: docker.io/sebgad/restainer:latest
    env:
      - name: RESTIC_TAG
        value: jellyfin-config
      - name: RESTIC_FORGET_ARGS
        value: --keep-daily 28 --keep-weekly 12 --keep-monthly 12 --group-by paths --prune
      - name: RESTIC_PASSWORD
        valueFrom:
          secretKeyRef:
            name: jellyfin
            key: restic_pw
      - name: TERM
        value: xterm
      - name: BACKUP_CRON
        value: "0 5 * * *"
      - name: CHECK_CRON
        value: "0 22 * * *"
    args:
      - tail
      - -fn0
      - /var/log/cron.log
    volumeMounts:
      - mountPath: /mnt/repo
        name: mnt-jellyfin-backup-redundant-host-path
      - mountPath: /data
        name: mnt-jellyfin-config
      - mountPath: /etc/timezone
        name: etc-timezone
      - mountPath: /etc/localtime
        name: etc-localtime
  - name: backup-redundant-media
    image: docker.io/sebgad/restainer:latest
    env:
      - name: RESTIC_TAG
        value: jellyfin-media
      - name: RESTIC_FORGET_ARGS
        value: --keep-daily 28 --keep-weekly 12 --keep-monthly 12 --group-by paths --prune
      - name: RESTIC_PASSWORD
        valueFrom:
          secretKeyRef:
            name: jellyfin
            key: restic_pw
      - name: TERM
        value: xterm
      - name: BACKUP_CRON
        value: "0 5 * * *"
      - name: CHECK_CRON
        value: "0 22 * * *"
    args:
      - tail
      - -fn0
      - /var/log/cron.log
    volumeMounts:
      - mountPath: /mnt/repo
        name: mnt-jellyfin-backup-redundant-media-host-path
      - mountPath: /data
        name: mnt-jellyfin-media
      - mountPath: /etc/timezone
        name: etc-timezone
      - mountPath: /etc/localtime
        name: etc-localtime
  volumes:
  - hostPath:
      path: /etc/timezone
      type: Directory
    name: etc-timezone
  - hostPath:
      path: /etc/localtime
      type: Directory
    name: etc-localtime
  - hostPath:
      path: /opt/pods/jellyfin/config
      type: Directory
    name: mnt-jellyfin-config
  - hostPath:
      path: /opt/pods/jellyfin/cache
      type: Directory
    name: mnt-jellyfin-cache
  - hostPath:
      path: /mnt/clouddrive/jellyfin
      type: Directory
    name: mnt-jellyfin-media
  - hostPath:
      path: /mnt/clouddrive_backup/backup/jellyfin/opt
      type: Directory
    name: mnt-jellyfin-backup-config-host-path
  - hostPath:
      path: /mnt/clouddrive_backup/backup/jellyfin/media
      type: Directory
    name: mnt-jellyfin-backup-media-host-path
  - hostPath:
      path: /mnt/clouddrive_backup/backup_redundant/jellyfin/opt
      type: Directory
    name: mnt-jellyfin-backup-redundant-host-path
  - hostPath:
      path: /mnt/clouddrive_backup/backup_redundant/jellyfin/media
      type: Directory
    name: mnt-jellyfin-backup-redundant-media-host-path
