apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/backend: registry
  labels:
    app: jellyfin
  name: jellyfin
spec:
  restartPolicy: always
  containers:
  - name: backend
    image: docker.io/jellyfin/jellyfin:latest
    ports:
    - containerPort: 8096
      hostPort: 8096
    volumeMounts:
    - mountPath: /config
      name: mnt-jellyfin-backend-config-path
    - mountPath: /cache
      name: mnt-jellyfin-backend-cache-path
    - mountPath: /media
      name: mnt-jellyfin-backend-media-path
  volumes:
  - hostPath:
      path: /etc/timezone
      type: Directory
    name: etc-timezone
  - hostPath:
      path: /etc/localtime
      type: Directory
    name: etc-localtime
  - hostPath:
      path: /kubernetes/jellyfin/config
      type: Directory
    name: mnt-jellyfin-backend-config-path
  - hostPath:
      path: /kubernetes/jellyfin/cache
      type: Directory
    name: mnt-jellyfin-backend-cache-path
  - hostPath:
      path: /kubernetes/jellyfin/media
      type: Directory
    name: mnt-jellyfin-backend-media-path
