# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.9.3
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/backend: registry
    io.containers.autoupdate/database: registry
    io.containers.autoupdate/image-previewer: registry
    io.containers.autoupdate/redis: registry
    io.containers.autoupdate/webserver: registry
    io.containers.autoupdate/antivirus: registry
    io.containers.autoupdate/backup-config: registry
    io.containers.autoupdate/backup-data: registry
    io.containers.autoupdate/backup-redundant-config: registry
    io.containers.autoupdate/backup-redundant-data: registry
  labels:
    app: nextcloud
  name: nextcloud
spec:
  containers:
    - name: database
      image: docker.io/library/mariadb:latest
      args:
        - mariadbd
      env:
        - name: MARIADB_USER
          value: nextadmin
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud
              key: database_root_pw
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud
              key: database_user_pw
        - name: MARIADB_DATABASE
          value: nextcloud
      volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: mnt-nextcloud-database-entrypoint-path
        - mountPath: /var/lib/mysql
          name: mnt-nextcloud-database-lib-path
    - name: antivirus
      image: docker.io/clamav/clamav
    - name: redis
      image: docker.io/library/redis:latest
      env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud
              key: redis_pw
      command: ["redis-server"]
      args: ["--requirepass", "$(REDIS_PASSWORD)"]
      volumeMounts:
        - mountPath: /data
          name: mnt-nextcloud-redis-persistance-path
    - name: image-previewer
      image: docker.io/h2non/imaginary:latest
      args:
        - "-enable-url-source"
        - "-concurrency"
        - "50"
      env:
        - name: PORT
          value: 8000
      securityContext: {}
    - name: backend
      image: docker.io/library/nextcloud
      ports:
        - containerPort: 80
          hostPort: 8083
      volumeMounts:
        - mountPath: /var/www/html
          name: mnt-nextcloud-backend-html-path
        - mountPath: /var/www/html/config
          name: mnt-nextcloud-backend-config-path
        - mountPath: /var/www/html/data
          name: mnt-nextcloud-backend-data-path
    - name: backup-config
      image: docker.io/sebgad/restainer:latest
      env:
        - name: MARIADB_DATABASE
          value: nextcloud
        - name: MARIADB_BACKUP_USER
          value: nextadmin
        - name: MARIADB_BACKUP_PW
          valueFrom:
            secretKeyRef:
              name: nextcloud
              key: database_user_pw
        - name: RESTIC_TAG
          value: nextcloud-config
        - name: RESTIC_FORGET_ARGS
          value: --keep-daily 28 --keep-weekly 12 --keep-monthly 12 --group-by paths --prune
        - name: RESTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud
              key: restic_pw
        - name: TERM
          value: xterm
        - name: BACKUP_CRON
          value: "0 5 * * *"
        - name: CHECK_CRON
          value: "0 22 * * *"
      args:
        - tail
        - -fn0
        - /var/log/cron.log
      volumeMounts:
        - mountPath: /mnt/repo
          name: mnt-clouddrive-backup-nextcloud-opt
        - mountPath: /data
          name: mnt-nextcloud-backup-data-path
        - mountPath: /etc/timezone
          name: etc-timezone
        - mountPath: /etc/localtime
          name: etc-localtime
        - mountPath: /var/log
          name: mnt-nextcloud-backup-config-log-path
    - name: backup-data
      image: docker.io/sebgad/restainer:latest
      env:
        - name: RESTIC_TAG
          value: nextcloud-data
        - name: RESTIC_FORGET_ARGS
          value: --keep-daily 28 --keep-weekly 12 --keep-monthly 12 --group-by paths --prune
        - name: RESTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud
              key: restic_pw
        - name: TERM
          value: xterm
        - name: BACKUP_CRON
          value: "0 5 * * *"
        - name: CHECK_CRON
          value: "0 22 * * *"
      args:
        - tail
        - -fn0
        - /var/log/cron.log
      volumeMounts:
        - mountPath: /mnt/repo
          name: mnt-clouddrive-backup-nextcloud-data
        - mountPath: /data
          name: mnt-nextcloud-backend-data-path
        - mountPath: /etc/timezone
          name: etc-timezone
        - mountPath: /etc/localtime
          name: etc-localtime
        - mountPath: /var/log
          name: mnt-nextcloud-backup-data-log-path
    - name: backup-redundant-config
      image: docker.io/sebgad/restainer:latest
      env:
        - name: MARIADB_DATABASE
          value: nextcloud
        - name: MARIADB_BACKUP_USER
          value: nextadmin
        - name: MARIADB_BACKUP_PW
          valueFrom:
            secretKeyRef:
              name: nextcloud
              key: database_user_pw
        - name: RESTIC_TAG
          value: nextcloud-config
        - name: RESTIC_FORGET_ARGS
          value: --keep-daily 28 --keep-weekly 12 --keep-monthly 12 --group-by paths --prune
        - name: RESTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud
              key: restic_pw
        - name: TERM
          value: xterm
        - name: BACKUP_CRON
          value: "0 5 * * *"
        - name: CHECK_CRON
          value: "0 22 * * *"
      args:
        - tail
        - -fn0
        - /var/log/cron.log
      volumeMounts:
        - mountPath: /mnt/repo
          name: mnt-nextcloud-backup-host-path
        - mountPath: /data
          name: mnt-nextcloud-backup-data-path
        - mountPath: /etc/timezone
          name: etc-timezone
        - mountPath: /etc/localtime
          name: etc-localtime
        - mountPath: /var/log
          name: mnt-nextcloud-backup-config-redundant-log-path
    - name: backup-redundant-data
      image: docker.io/sebgad/restainer:latest
      env:
        - name: RESTIC_TAG
          value: nextcloud-data
        - name: RESTIC_FORGET_ARGS
          value: --keep-daily 28 --keep-weekly 12 --keep-monthly 12 --group-by paths --prune
        - name: RESTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud
              key: restic_pw
        - name: TERM
          value: xterm
        - name: BACKUP_CRON
          value: "0 5 * * *"
        - name: CHECK_CRON
          value: "0 22 * * *"
      args:
        - tail
        - -fn0
        - /var/log/cron.log
      volumeMounts:
        - mountPath: /mnt/repo
          name: mnt-nextcloud-backup-redundant-host-path
        - mountPath: /data
          name: mnt-nextcloud-backend-data-path
        - mountPath: /etc/timezone
          name: etc-timezone
        - mountPath: /etc/localtime
          name: etc-localtime
        - mountPath: /var/log
          name: mnt-nextcloud-backup-data-redundant-log-path
  volumes:
    - hostPath:
        path: /etc/timezone
        type: Directory
      name: etc-timezone
    - hostPath:
        path: /etc/localtime
        type: Directory
      name: etc-localtime
    - hostPath:
        path: /opt/pods/nextcloud/redis/persistance
        type: Directory
      name: mnt-nextcloud-redis-persistance-path
    - hostPath:
        path: /opt/pods/nextcloud/backend/html
        type: Directory
      name: mnt-nextcloud-backend-html-path
    - hostPath:
        path: /opt/pods/nextcloud/backend/config
        type: Directory
      name: mnt-nextcloud-backend-config-path
    - hostPath:
        path: /mnt/clouddrive/nextcloud
        type: Directory
      name: mnt-nextcloud-backend-data-path
    - hostPath:
        path: /opt/pods/nextcloud/database/entrypoint
        type: Directory
      name: mnt-nextcloud-database-entrypoint-path
    - hostPath:
        path: /opt/pods/nextcloud/database/data
        type: Directory
      name: mnt-nextcloud-database-lib-path
    - hostPath:
        path: /opt/pods/nextcloud
        type: Directory
      name: mnt-nextcloud-backup-data-path
    - hostPath:
        path: /mnt/clouddrive_backup/backup/nextcloud/opt
        type: Directory
      name: mnt-clouddrive-backup-nextcloud-opt
    - hostPath:
        path: /mnt/clouddrive_backup/backup/nextcloud/data
        type: Directory
      name: mnt-clouddrive-backup-nextcloud-data
    - hostPath:
        path: /mnt/clouddrive_backup/backup_redundant/nextcloud/opt
        type: Directory
      name: mnt-nextcloud-backup-host-path
    - hostPath:
        path: /mnt/clouddrive_backup/backup_redundant/nextcloud/data
        type: Directory
      name: mnt-nextcloud-backup-redundant-host-path
    - hostPath:
        path: /opt/pods/nextcloud/backup_config
        type: Directory
      name: mnt-nextcloud-backup-config-log-path
    - hostPath:
        path: /opt/pods/nextcloud/backup_config_redundant
        type: Directory
      name: mnt-nextcloud-backup-config-redundant-log-path
    - hostPath:
        path: /opt/pods/nextcloud/backup_data
        type: Directory
      name: mnt-nextcloud-backup-data-log-path
    - hostPath:
        path: /opt/pods/nextcloud/backup_data_redundant
        type: Directory
      name: mnt-nextcloud-backup-data-redundant-log-path

