# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.9.3
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/backend: registry
    io.containers.autoupdate/database: registry
    io.containers.autoupdate/tika: registry
    io.containers.autoupdate/redis: registry
    io.containers.autoupdate/gotenberg: registry
  labels:
    app: paperless-ngx
  name: paperless-ngx
spec:
  restartPolicy: always
  containers:
    - name: backend
      image: ghcr.io/paperless-ngx/paperless-ngx:latest
      env:
        - name: PAPERLESS_EMAIL_TASK_CRON
          value: "*/10 * * * *"
        - name: PAPERLESS_REDIS
          valueFrom:
            secretKeyRef:
              name: ngx_paperless
              key: redis_url_pw
        - name: PAPERLESS_DBHOST
          value: 127.0.0.1
        - name: PAPERLESS_OCR_USER_ARGS
          value: '{"continue_on_soft_render_error": true}'
        - name: PAPERLESS_CONSUMER_POLLING
          value: 60
        - name: PAPERLESS_TIKA_ENABLED
          value: 1
        - name: PAPERLESS_TIKA_GOTENBERG_ENDPOINT
          value: "http://localhost:3000"
        - name: PAPERLESS_TIKA_ENDPOINT
          value: "http://localhost:9998"
        - name: POSTGRES_DB
          value: paperless
        - name: POSTGRES_USER
          value: paperless
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ngx_paperless
              key: postgres_pw
        - name: PAPERLESS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ngx_paperless
              key: paperless_secret_key
        - name: PAPERLESS_URL
          value: "https://paperless-ngx.sebastianyue.ddns.net"
        - name: PAPERLESS_USE_X_FORWARDED_HOST
          value: true
        - name: PAPERLESS_USE_X_FORWARD_PORT
          value: true
        - name: PAPERLESS_PROXY_SSL_HEADER
          value: '["HTTP_X_FORWARDED_PROTO", "https"]'
        - name: PAPERLESS_CONSUMER_DELETE_DUPLICATES
          value: true
        - name: PAPERLESS_DATE_PARSER_LANGUAGES
          value: "de+en"
        - name: PAPERLESS_OCR_LANGUAGE
          value: "deu+eng"
      ports:
        - containerPort: 8000
          hostPort: 8090
      volumeMounts:
        - mountPath: /usr/src/paperless/data
          name: mnt-paperless-ngx-server-data-path
        - mountPath: /usr/src/paperless/media
          name: mnt-paperless-ngx-server-media-path
        - mountPath: /usr/src/paperless/export
          name: mnt-paperless-ngx-server-export-path
        - mountPath: /usr/src/paperless/consume
          name: mnt-paperless-ngx-server-consume-path
        - mountPath: /etc/timezone
          name: etc-timezone
          readOnly: true
        - mountPath: /etc/localtime
          name: etc-localtime
          readOnly: true
    - name: redis
      image: docker.io/library/redis
      env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ngx_paperless
              key: redis_pw
      command: ["redis-server"]
      args: ["--requirepass", "$(REDIS_PASSWORD)"]
      volumeMounts:
        - mountPath: /data
          name: mnt-paperless-ngx-redis-persistance-path
    - name: database
      image: docker.io/library/postgres:17
      env:
        - name: POSTGRES_DB
          value: paperless
        - name: POSTGRES_USER
          value: paperless
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ngx_paperless
              key: postgres_pw
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: mnt-paperless-ngx-database-path
        - mountPath: /etc/timezone
          name: etc-timezone
          readOnly: true
        - mountPath: /etc/localtime
          name: etc-localtime
          readOnly: true
    - name: tika
      image: docker.io/apache/tika:latest
    - name: gotenberg
      image: docker.io/gotenberg/gotenberg:8.22
      commands:
        - "gotenberg"
        - "--chromium-disable-javascript=true"
        - "--chromium-allow-list=file:///tmp/.*"
  volumes:
    - hostPath:
        path: /etc/timezone
        type: File
      name: etc-timezone
    - hostPath:
        path: /etc/localtime
        type: File
      name: etc-localtime
    - hostPath:
        path: /kubernetes-fast/paperless-ngx/database
        type: Directory
      name: mnt-paperless-ngx-database-path
    - hostPath:
        path: /kubernetes-fast/paperless-ngx/redis
        type: Directory
      name: mnt-paperless-ngx-redis-persistance-path
    - hostPath:
        path: /kubernetes-fast/paperless-ngx/backend/data
        type: Directory
      name: mnt-paperless-ngx-server-data-path
    - hostPath:
        path: /kubernetes/paperless-ngx/backend/media
        type: Directory
      name: mnt-paperless-ngx-server-media-path
    - hostPath:
        path: /kubernetes-fast/paperless-ngx/backend/export
        type: Directory
      name: mnt-paperless-ngx-server-export-path
    - hostPath:
        path: /kubernetes-fast/paperless-ngx/backend/consume
        type: Directory
      name: mnt-paperless-ngx-server-consume-path
