# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.9.3
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /opt/pods/vaultwarden/database/data:Z
    io.containers.autoupdate/backend: registry
    io.containers.autoupdate/database: registry
  labels:
    app: vaultwarden
  name: vaultwarden
spec:
  restartPolicy: always
  containers:
    - name: backend
      image: docker.io/vaultwarden/server:latest
      env:
        - name: INVITATIONS_ALLOWED
          value: "false"
        - name: ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: vaultwarden
              key: admin_token
        - name: LOG_FILE
          value: /data/vaultwarden.log
        - name: YUBICO_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: vaultwarden
              key: yubico_client_id
        - name: ENABLE_DB_WAL
          value: "false"
        - name: YUBICO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: vaultwarden
              key: yubico_secret
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: vaultwarden
              key: database_url
        - name: WEBSOCKET_ENABLED
          value: "false"
        - name: TIME_ZONE
          value: Europe/Berlin
        - name: SIGNUPS_ALLOWED
          value: "false"
      ports:
        - containerPort: 80
          hostPort: 8082
      volumeMounts:
        - mountPath: /data
          name: mnt-vaultwarden-backend-data-path
        - mountPath: /etc/timezone
          name: etc-timezone
          readOnly: true
        - mountPath: /etc/localtime
          name: etc-localtime
          readOnly: true
    - name: database
      image: docker.io/library/mariadb:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vaultwarden
              key: database_root_pw
        - name: MARIADB_USER
          value: vaultwarden
        - name: MARIADB_DATABASE
          value: vaultwarden
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vaultwarden
              key: database_user_pw
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mnt-vaultwarden-database-lib-path
        - mountPath: /docker-entrypoint-initdb.d
          name: mnt-vaultwarden-database-entrypoint-path
      args:
        - mariadbd
  volumes:
    - hostPath:
        path: /etc/timezone
        type: File
      name: etc-timezone
    - hostPath:
        path: /etc/localtime
        type: File
      name: etc-localtime
    - hostPath:
        path: /kubernetes-fast/vaultwarden/database/data
        type: Directory
      name: mnt-vaultwarden-database-lib-path
    - hostPath:
        path: /kubernetes-fast/vaultwarden/database/entrypoint
        type: Directory
      name: mnt-vaultwarden-database-entrypoint-path
    - hostPath:
        path: /kubernetes-fast/vaultwarden/vaultwarden
        type: Directory
      name: mnt-vaultwarden-backend-data-path


