# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.9.3
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/database: registry
    io.containers.autoupdate/webserver: registry
    io.containers.autoupdate/backup: image
    io.containers.autoupdate/backup-redundant: image
  labels:
    app: wordpress
  name: wordpress
spec:
  containers:
    - name: database
      image: docker.io/library/mariadb:latest
      args:
        - mariadbd
      env:
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: db_wordpress_pw
        - name: MARIADB_DATABASE
          value: wordpress
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: db_root_pw
        - name: MARIADB_USER
          value: wordpress
      ports:
        - containerPort: 80
          hostPort: 8081
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mnt-wordpress-database-lib-path
        - mountPath: /docker-entrypoint-initdb.d
          name: mnt-wordpress-database-entrypoint-path
    - name: webserver
      image: docker.io/library/wordpress:latest
      args:
        - apache2-foreground
      env:
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: db_wordpress_pw
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_NAME
          value: wordpress
      volumeMounts:
        - mountPath: /var/www/html
          name: mnt-wordpress-webserver-html-path
    - name: backup
      image: docker.io/sebgad/restainer:latest
      env:
        - name: MARIADB_DATABASE
          value: wordpress
        - name: MARIADB_BACKUP_USER
          value: wordpress
        - name: MARIADB_BACKUP_PW
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: db_wordpress_pw
        - name: RESTIC_TAG
          value: wordpress
        - name: RESTIC_FORGET_ARGS
          value: --keep-daily 28 --keep-weekly 12 --keep-monthly 12 --group-by paths --prune
        - name: RESTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: restic_pw
        - name: TERM
          value: xterm
        - name: BACKUP_CRON
          value: "0 5 * * *"
        - name: CHECK_CRON
          value: "0 22 * * *"
      args:
        - tail
        - -fn0
        - /var/log/cron.log
      volumeMounts:
        - mountPath: /mnt/repo
          name: mnt-wordpress-backup-host-path
        - mountPath: /data
          name: mnt-wordpress-webserver-html-path
        - mountPath: /etc/timezone
          name: etc-timezone
        - mountPath: /etc/localtime
          name: etc-localtime
    - name: backup-redundant
      image: docker.io/sebgad/restainer:latest
      env:
        - name: RESTIC_TAG
          value: wordpress
        - name: RESTIC_FORGET_ARGS
          value: --keep-daily 28 --keep-weekly 12 --keep-monthly 12 --group-by paths --prune
        - name: RESTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: restic_pw
        - name: TERM
          value: xterm
        - name: BACKUP_CRON
          value: "0 5 * * *"
        - name: CHECK_CRON
          value: "0 22 * * *"
      args:
        - tail
        - -fn0
        - /var/log/cron.log
      volumeMounts:
        - mountPath: /mnt/repo
          name: mnt-wordpress-backup-redundant-host-path
        - mountPath: /data
          name: mnt-wordpress-webserver-html-path
        - mountPath: /etc/timezone
          name: etc-timezone
        - mountPath: /etc/localtime
          name: etc-localtime
  volumes:
    - hostPath:
        path: /etc/timezone
        type: File
      name: etc-timezone
    - hostPath:
        path: /etc/localtime
        type: File
      name: etc-localtime
    - hostPath:
        path: /opt/pods/wordpress/database/data
        type: Directory
      name: mnt-wordpress-database-lib-path
    - hostPath:
        path: /opt/pods/wordpress/database/entrypoint
        type: Directory
      name: mnt-wordpress-database-entrypoint-path
    - hostPath:
        path: /opt/pods/wordpress/webserver
        type: Directory
      name: mnt-wordpress-webserver-html-path
    - hostPath:
        path: /mnt/clouddrive_backup/backup/wordpress
        type: Directory
      name: mnt-wordpress-backup-host-path
    - hostPath:
        path: /mnt/clouddrive_backup/backup_redundant/wordpress
        type: Directory
      name: mnt-wordpress-backup-redundant-host-path
    - hostPath:
        path: /opt/pods/wordpress/backup
        type: Directory
      name: mnt-wordpress-backup-log-path
    - hostPath:
        path: /opt/pods/wordpress/backup_redundant
        type: Directory
      name: mnt-wordpress-backup-redundant-log-path

